language: python
python:
    - "2.7"
    - "3.5"

before_install:
    - echo Installing Anaconda. Path is $PATH
    - cd
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/archive/Anaconda2-4.2.0-Linux-x86_64.sh -O anaconda.sh;
      else
        wget https://repo.continuum.io/archive/Anaconda3-4.2.0-Linux-x86_64.sh -O anaconda.sh;
      fi
    - bash anaconda.sh -b -p $HOME/anaconda
    - export PATH="$HOME/anaconda/bin:$PATH"
    - echo Done installing Anaconda. Path is $PATH
    - echo Install scala
    - wget http://www.scala-lang.org/files/archive/scala-2.10.4.tgz
    - tar -xvf scala-2.10.4.tgz
    - export SCALA_HOME=~/scala-2.10.4
    - echo Installing Spark
    - wget http://d3kbcqa49mib13.cloudfront.net/spark-1.6.0-bin-hadoop2.6.tgz
    - tar -xvf spark-1.6.0-bin-hadoop2.6.tgz
    - export SPARK_HOME=~/spark-1.6.0-bin-hadoop2.6
    - export PIXIEDUST_HOME=~/pixiedust-test-$TRAVIS_PYTHON_VERSION

install:
    - conda create -y -q -n pixiedust-travis-test python=$TRAVIS_PYTHON_VERSION
    - source activate pixiedust-travis-test
    - conda install -y jupyter matplotlib pandas seaborn requests yaml
    - cd $TRAVIS_BUILD_DIR
    - python setup.py install

script:
    - python $TRAVIS_BUILD_DIR/tests/runPixiedustNotebooks.py 

sudo: false

notifications:
  slack:
    rooms:
      secure: "ZbPB01PfMrOAnneykn9CQTYSx5nMTPANf6Jn949T7enho/xc7oU2SXONb7erO6BeyHb27AGTVlOkfeFRH/ekUt9QOnBZU1ZdomkGXaD96ZVHk2uvtlYsdw16l7sS7InQrhveLAGPCF2+9TChwciwSpT7/dZ1Smf0BShrhlCfLvp
8Z26DX9k31TSGvsYmuXLCHJqnxVpMVof22az9dLLT/eMD11zwWYyOR3aiYhx8YOiTM8hSQWxjSuD4OQpH1ng/BYANR+DJSWyYUCELuoEx9a7QqKU4U7uIUo0rifUbtD0uBM4+P7rnoircAto0f1mmJNh09CUgCu4YeXHFy7XCAXRAhwUE9Mgoy
4T20lQDUGw35SJuyGuay8tQnE1QJJUn+2ThHgfZ33eGU9M1G9zRyCRwn33vVtZhtdrs1V0AdZ8VCI0tG0+bVb4NF4rTdgBhBRBSNaegXU61fe4BzP//b5CwPh1E6a2N/lTxkuRSBfcOOPRXkHz2DpUUvUStDrtsa8ux3PnfqYqoFlysDIhR2/E
UAp6QB7dKIdd0/+NF6eGvIzGYuKMcVmINdtAv3AE+unwYPN2F9VS/j0sWEwLhrrgHiYW7VxIBDnIaKCvf59rHz+siisrAiZS6OPzqsUWdOceNXAYZ31cC05PAtTjyYaYkAff8QMpIwMBDsSWHVAQ="
