language: python
python:
    -"2.7"
    -"3.5"

install:
    - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION pip nbconvert
    - source activate test-env
    - python setup.py install

script:
    - python $TRAVIS_BUILD_DIR/tests/runPixiedustNotebooks.py

sudo: false